#!/bin/bash -e

# remove the default site
sudo rm -f /etc/nginx/conf.d/default.conf

# install the folio site
sudo cp -f /home/mario/folio/nginx/folio.conf /etc/nginx/conf.d/folio.conf

# replace the master configuration
sudo cp -f nginx/nginx.conf /etc/nginx/nginx.conf
sudo chmod 0600 /etc/nginx/nginx.conf
sudo chown root:root /etc/nginx/nginx.conf
sudo nginx -t
sudo service nginx reload

